/* 영문 팀명 → { ko: 한국어명, flag: 국기 이모지, iso: flagcdn 코드, c: 대표색, c2: 보조색 }
   국기는 윈도우에서 이모지가 안 보여 iso 기반 이미지(flagcdn)로 렌더링한다. */
window.TEAM_INFO = {
  "Algeria": { ko: "알제리", flag: "🇩🇿", iso: "dz", c: "#1F9E5E", c2: "#E0414A" },
  "Argentina": { ko: "아르헨티나", flag: "🇦🇷", iso: "ar", c: "#6CACE4", c2: "#F6B40E" },
  "Australia": { ko: "호주", flag: "🇦🇺", iso: "au", c: "#F5C518", c2: "#1F8A4C" },
  "Austria": { ko: "오스트리아", flag: "🇦🇹", iso: "at", c: "#E63A4B", c2: "#B82A38" },
  "Belgium": { ko: "벨기에", flag: "🇧🇪", iso: "be", c: "#F0C419", c2: "#E03A3E" },
  "Bosnia and Herzegovina": { ko: "보스니아", flag: "🇧🇦", iso: "ba", c: "#3B6FE0", c2: "#F5C518" },
  "Brazil": { ko: "브라질", flag: "🇧🇷", iso: "br", c: "#1FB955", c2: "#FCD23B" },
  "Canada": { ko: "캐나다", flag: "🇨🇦", iso: "ca", c: "#EE4B4B", c2: "#B53636" },
  "Cape Verde": { ko: "카보베르데", flag: "🇨🇻", iso: "cv", c: "#3F6FC0", c2: "#F5C518" },
  "Colombia": { ko: "콜롬비아", flag: "🇨🇴", iso: "co", c: "#FCD116", c2: "#1F4FB6" },
  "Croatia": { ko: "크로아티아", flag: "🇭🇷", iso: "hr", c: "#E84855", c2: "#2E64C0" },
  "Curaçao": { ko: "쿠라사오", flag: "🇨🇼", iso: "cw", c: "#2E64C0", c2: "#F4D03F" },
  "Czech Republic": { ko: "체코", flag: "🇨🇿", iso: "cz", c: "#3F6FC0", c2: "#D7202A" },
  "DR Congo": { ko: "콩고민주공화국", flag: "🇨🇩", iso: "cd", c: "#2E9BE6", c2: "#F4D03F" },
  "Ecuador": { ko: "에콰도르", flag: "🇪🇨", iso: "ec", c: "#FFD23B", c2: "#2E64C0" },
  "Egypt": { ko: "이집트", flag: "🇪🇬", iso: "eg", c: "#D0303F", c2: "#C9A24B" },
  "England": { ko: "잉글랜드", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", iso: "gb-eng", c: "#E94B4B", c2: "#14307A" },
  "France": { ko: "프랑스", flag: "🇫🇷", iso: "fr", c: "#3B6FE0", c2: "#EF4135" },
  "Germany": { ko: "독일", flag: "🇩🇪", iso: "de", c: "#F5C518", c2: "#E0414A" },
  "Ghana": { ko: "가나", flag: "🇬🇭", iso: "gh", c: "#F5C518", c2: "#1FA85A" },
  "Haiti": { ko: "아이티", flag: "🇭🇹", iso: "ht", c: "#3457C7", c2: "#D0303F" },
  "Iran": { ko: "이란", flag: "🇮🇷", iso: "ir", c: "#2B9E5E", c2: "#E0414A" },
  "Iraq": { ko: "이라크", flag: "🇮🇶", iso: "iq", c: "#2B9E5E", c2: "#D0303F" },
  "Ivory Coast": { ko: "코트디부아르", flag: "🇨🇮", iso: "ci", c: "#FF8A2A", c2: "#1FA85A" },
  "Japan": { ko: "일본", flag: "🇯🇵", iso: "jp", c: "#E33B5A", c2: "#2A2F45" },
  "Jordan": { ko: "요르단", flag: "🇯🇴", iso: "jo", c: "#1F9E5E", c2: "#D0303F" },
  "Mexico": { ko: "멕시코", flag: "🇲🇽", iso: "mx", c: "#19A463", c2: "#E0414A" },
  "Morocco": { ko: "모로코", flag: "🇲🇦", iso: "ma", c: "#C92D38", c2: "#1F8A4C" },
  "Netherlands": { ko: "네덜란드", flag: "🇳🇱", iso: "nl", c: "#FF7A1A", c2: "#2E4FA0" },
  "New Zealand": { ko: "뉴질랜드", flag: "🇳🇿", iso: "nz", c: "#3F6FD6", c2: "#D0303F" },
  "Norway": { ko: "노르웨이", flag: "🇳🇴", iso: "no", c: "#E0414A", c2: "#2E64C0" },
  "Panama": { ko: "파나마", flag: "🇵🇦", iso: "pa", c: "#3F6FC0", c2: "#D0303F" },
  "Paraguay": { ko: "파라과이", flag: "🇵🇾", iso: "py", c: "#E0414A", c2: "#2E64C0" },
  "Portugal": { ko: "포르투갈", flag: "🇵🇹", iso: "pt", c: "#2B9E5E", c2: "#E03A3E" },
  "Qatar": { ko: "카타르", flag: "🇶🇦", iso: "qa", c: "#9B2247", c2: "#6E1730" },
  "Saudi Arabia": { ko: "사우디아라비아", flag: "🇸🇦", iso: "sa", c: "#1FA85A", c2: "#0E6B3C" },
  "Scotland": { ko: "스코틀랜드", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", iso: "gb-sct", c: "#3F7BD6", c2: "#2A4FA0" },
  "Senegal": { ko: "세네갈", flag: "🇸🇳", iso: "sn", c: "#2B9E5E", c2: "#F4D03F" },
  "South Africa": { ko: "남아공", flag: "🇿🇦", iso: "za", c: "#1FA85A", c2: "#F5C518" },
  "South Korea": { ko: "대한민국", flag: "🇰🇷", iso: "kr", c: "#D03B4B", c2: "#2E64C0" },
  "Spain": { ko: "스페인", flag: "🇪🇸", iso: "es", c: "#E03A3E", c2: "#F7C600" },
  "Sweden": { ko: "스웨덴", flag: "🇸🇪", iso: "se", c: "#4A90C2", c2: "#F5C518" },
  "Switzerland": { ko: "스위스", flag: "🇨🇭", iso: "ch", c: "#E63A2E", c2: "#B22A22" },
  "Tunisia": { ko: "튀니지", flag: "🇹🇳", iso: "tn", c: "#E63A4B", c2: "#B82A38" },
  "Turkey": { ko: "튀르키예", flag: "🇹🇷", iso: "tr", c: "#E63A4B", c2: "#B82A38" },
  "United States": { ko: "미국", flag: "🇺🇸", iso: "us", c: "#5566C7", c2: "#C0303F" },
  "Uruguay": { ko: "우루과이", flag: "🇺🇾", iso: "uy", c: "#5FB3E6", c2: "#F4C430" },
  "Uzbekistan": { ko: "우즈베키스탄", flag: "🇺🇿", iso: "uz", c: "#2BB0B5", c2: "#1FB955" },
};
