/* 영문 팀명 → { ko: 한국어명, flag: 국기 이모지 } */
window.TEAM_INFO = {
  "Algeria": { ko: "알제리", flag: "🇩🇿" },
  "Argentina": { ko: "아르헨티나", flag: "🇦🇷" },
  "Australia": { ko: "호주", flag: "🇦🇺" },
  "Austria": { ko: "오스트리아", flag: "🇦🇹" },
  "Belgium": { ko: "벨기에", flag: "🇧🇪" },
  "Bosnia and Herzegovina": { ko: "보스니아", flag: "🇧🇦" },
  "Brazil": { ko: "브라질", flag: "🇧🇷" },
  "Canada": { ko: "캐나다", flag: "🇨🇦" },
  "Cape Verde": { ko: "카보베르데", flag: "🇨🇻" },
  "Colombia": { ko: "콜롬비아", flag: "🇨🇴" },
  "Croatia": { ko: "크로아티아", flag: "🇭🇷" },
  "Curaçao": { ko: "쿠라사오", flag: "🇨🇼" },
  "Czech Republic": { ko: "체코", flag: "🇨🇿" },
  "DR Congo": { ko: "콩고민주공화국", flag: "🇨🇩" },
  "Ecuador": { ko: "에콰도르", flag: "🇪🇨" },
  "Egypt": { ko: "이집트", flag: "🇪🇬" },
  "England": { ko: "잉글랜드", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  "France": { ko: "프랑스", flag: "🇫🇷" },
  "Germany": { ko: "독일", flag: "🇩🇪" },
  "Ghana": { ko: "가나", flag: "🇬🇭" },
  "Haiti": { ko: "아이티", flag: "🇭🇹" },
  "Iran": { ko: "이란", flag: "🇮🇷" },
  "Iraq": { ko: "이라크", flag: "🇮🇶" },
  "Ivory Coast": { ko: "코트디부아르", flag: "🇨🇮" },
  "Japan": { ko: "일본", flag: "🇯🇵" },
  "Jordan": { ko: "요르단", flag: "🇯🇴" },
  "Mexico": { ko: "멕시코", flag: "🇲🇽" },
  "Morocco": { ko: "모로코", flag: "🇲🇦" },
  "Netherlands": { ko: "네덜란드", flag: "🇳🇱" },
  "New Zealand": { ko: "뉴질랜드", flag: "🇳🇿" },
  "Norway": { ko: "노르웨이", flag: "🇳🇴" },
  "Panama": { ko: "파나마", flag: "🇵🇦" },
  "Paraguay": { ko: "파라과이", flag: "🇵🇾" },
  "Portugal": { ko: "포르투갈", flag: "🇵🇹" },
  "Qatar": { ko: "카타르", flag: "🇶🇦" },
  "Saudi Arabia": { ko: "사우디아라비아", flag: "🇸🇦" },
  "Scotland": { ko: "스코틀랜드", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  "Senegal": { ko: "세네갈", flag: "🇸🇳" },
  "South Africa": { ko: "남아공", flag: "🇿🇦" },
  "South Korea": { ko: "대한민국", flag: "🇰🇷" },
  "Spain": { ko: "스페인", flag: "🇪🇸" },
  "Sweden": { ko: "스웨덴", flag: "🇸🇪" },
  "Switzerland": { ko: "스위스", flag: "🇨🇭" },
  "Tunisia": { ko: "튀니지", flag: "🇹🇳" },
  "Turkey": { ko: "튀르키예", flag: "🇹🇷" },
  "United States": { ko: "미국", flag: "🇺🇸" },
  "Uruguay": { ko: "우루과이", flag: "🇺🇾" },
  "Uzbekistan": { ko: "우즈베키스탄", flag: "🇺🇿" },
};
